version: "3"

services:
  postgresql:
    container_name: postgres
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=web-forum

  redis:
    container_name: redis
    image: "redis:7"
    ports:
        - '6379:6379'