version: "3"

# docker exec -ti postgres psql -U postgres -h localhost -f /usr/src/app/migrations/0001_table_initialize.sql web-forum

services:
  postgresql:
    container_name: postgres
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=web-forum
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/usr/src/app
      - /custom/mount:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7
    ports:
      - '6379:6379'

  web-forum:
    container_name: web-forum
    image: golang:1.22
    depends_on:
      - postgresql
      - redis
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: >
      bash -c "go mod tidy &&
      echo 'go mod tidy -> OK!' &&
      go run main.go"

    ports:
      - '8080:8080'