### Send request with dynamic variables in request's body
POST http://localhost/api/admin/create
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRpdGlvbmFsIjoiYWNjZXNzIiwiZXhwaXJlc0F0IjoiMTcyNjU4MDIwNSIsImlkIjoxNTQ2MDY5M30.-68KY080M9YppT_LINU6IJW_owYqpTatO_VSwcsioOI

{
  "name": "123456",
  "description": "1234567"
}